fix: cascade delete on user deletion for `ai_web_app_thread` and `ai_web_app_prompt` tables (#16697)
<!-- Thanks so much for your PR, your contribution is appreciated! ❤️ -->

Closes: #16702

### Description:

Added a migration to fix foreign key constraints for AI web app tables. The migration updates the foreign key relationships for `ai_web_app_thread` and `ai_web_app_prompt` tables to include `CASCADE` on delete, which ensures that when a user is deleted, their associated AI threads and prompts are also removed. This fixes a bug where user deletion was being prevented due to these foreign key constraints.

Users were getting this error:

```
error: delete from "users" where "user_uuid" = $1 - update or delete on table "users" violates foreign key constraint "ai_web_app_thread_user_uuid_foreign" on table "ai_web_app_thread"
```

when requesting `DELETE /api/v1/org/user/:userUuid`

To reproduce:

1. create an AI thread from web 
2. try to delete the user from step 1